# Estadística Aplicada
## Alejandro Hernández Cerda 1903855
### Objetos en Python

In [3]:
alumno1=['Juan','Perez',23]

In [12]:
estadistica_g4=['Juan','Raul','Ximena','Alejandra']

In [13]:
estadistica_g4

['Juan', 'Raul', 'Ximena', 'Alejandra']

In [15]:
estadistica_g4[2]

'Ximena'

In [17]:
estadistica_g4[0]

'Juan'

In [20]:
estadistica_g4[0],estadistica_g4[2]

('Juan', 'Ximena')

In [22]:
estadistica_g4[0:3]

['Juan', 'Raul', 'Ximena']

In [36]:
estadistica_g4.append('Jaime')

In [26]:
estadistica_g4

['Juan', 'Raul', 'Ximena', 'Alejandra', 'Jaime', 'Jaime']

In [30]:
estadistica_g4

['Juan', 'Raul', 'Alejandra', 'Jaime', 'Jaime']

In [35]:
estadistica_g4.remove('Jaime')

In [38]:
estadistica_g4

['Juan', 'Raul', 'Alejandra', 'Jaime']

In [45]:
pip install yfinance

Note: you may need to restart the kernel to use updated packages.


In [48]:
import yfinance as yf

**ASI SE INSTALA UNA LIBRERIA** // **Y ASÍ SE LE CAMBIA EL NOMBRE PARA REDUCIRLO**

In [50]:
import numpy as np

In [61]:
edades=[12,23,34,45,56]

In [56]:
type(edades)

list

In [63]:
edades= np.array(edades)

In [65]:
np.sum(edades)

170

In [67]:
np.mean(edades)

34.0

In [68]:
np.prod(edades)

23647680

In [70]:
np.var(edades)

242.0

**VARIANZA POBLACIONAL PUES DDOF = 0**

In [71]:
np.var(edades,ddof=1)

302.5

**VARIANZA MUESTRAL PUES DDOF=1**

In [72]:
np.std(edades)

15.556349186104045

In [73]:
np.std(edades,ddof=1)

17.392527130926087

In [74]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [77]:
np.arange(0,101,15)

array([ 0, 15, 30, 45, 60, 75, 90])

In [79]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [83]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [85]:
np.full(8,6)

array([6, 6, 6, 6, 6, 6, 6, 6])

In [87]:
np.random.randint(0,25,10)

array([ 2,  2, 23,  8, 24, 18,  0, 23, 10, 11])

**SEMILLA, ESTO ES PARA QUE AL MOMENTO DE GENERAR NUMEROS ALEATORIOS SEAN SIEMPRE LOS MISMOS**

In [92]:
np.random.seed(5)
np.random.randint(0,25,10)

array([ 3, 14, 15,  6, 22, 16,  9,  8,  4,  7])

In [94]:
aleatorios=np.random.randint(0,25,10)