# Estadistica Aplicada
## Alejandro Hernández Cerda 1903855
### 3ra Sesión


In [2]:
import numpy as np

In [4]:
np.random.seed(30)
aleatorios = np.random.randint(0,20,10)

In [6]:
aleatorios = np.sort(aleatorios)

In [8]:
aleatorios

array([ 2,  3,  5,  5,  9, 12, 13, 13, 14, 17])

In [9]:
aleatorios[2]

5

In [11]:
aleatorios[[2,3]]

array([5, 5])

In [13]:
aleatorios[aleatorios>10]

array([12, 13, 13, 14, 17])

In [30]:
np.random.seed(315)
aleatorios2=np.random.randint(21,50,10)

In [31]:
aleatorios2

array([30, 24, 30, 23, 44, 23, 31, 40, 24, 35])

**Convertir a aleatorios2 en un arreglo, le vamos a calcular la media y vamos a redondear a un decimal**
# FUNCIÓN

In [32]:
round(np.mean(np.array(aleatorios2)),1)

30.4

**Esto se debe a que estamos tratando de redondear la media del arreglo a un decimal, por eso el ,1**
# MÉTODO

In [33]:
np.array(aleatorios2).mean().round(1)

30.4

# FUNCIONES
**np.mean()
np.sum()
np.var()
np.var(,ddof)
np.prod()
np.std()
np.arange()**

# TUPLAS

In [34]:
Tupla1 = (23,45,"libro")

In [35]:
type(Tupla1)

tuple

In [36]:
Tupla1[2]

'libro'

# Diccionarios

In [44]:
alumno1_dic={'Nombre':'Juan','Apellido':'Perez','Edad':23}

In [45]:
type(alumno_dic)

dict

In [46]:
alumno1_dic

{'Nombre': 'Juan', 'Apellido': 'Perez', 'Edad': 23}

In [47]:
alumno1_dic['Nombre']

'Juan'

In [48]:
alumno1_dic['Apellido']

'Perez'

In [49]:
estadistica_g5={'Nombre':['Ale','Jaime','Teo'],'Apellido':['Leos','Lara','Leal'],
                'Edad':[23,28,17]}

In [50]:
estadistica_g5['Nombre']

['Ale', 'Jaime', 'Teo']

In [53]:
estadistica_g5.keys()

dict_keys(['Nombre', 'Apellido', 'Edad'])

In [54]:
estadistica_g5.values()

dict_values([['Ale', 'Jaime', 'Teo'], ['Leos', 'Lara', 'Leal'], [23, 28, 17]])

# PANDAS
## DATAFRAMES

In [55]:
import pandas as pd

In [56]:
alumno1 = ['Juan', 'Pérez', 23]
alumno2 = ['Raúl', 'González', 17]
alumno3 = ['Jimena', 'Rosas', 20]
alumno4 = ['Alejandra', 'Saldaña', 21]

In [57]:
clase_estadistica=[alumno1,alumno2,alumno3,alumno4]

In [58]:
clase_estadistica

[['Juan', 'Pérez', 23],
 ['Raúl', 'González', 17],
 ['Jimena', 'Rosas', 20],
 ['Alejandra', 'Saldaña', 21]]

In [65]:
clase_estadistica=pd.DataFrame(clase_estadistica,columns = ["Nombre","Apellido","Edad"])

In [66]:
clase_estadistica['Edad en días']=clase_estadistica['Edad']*365

In [67]:
clase_estadistica

Nombre  Apellido  Edad  Edad en días
0       Juan     Pérez    23          8395
1       Raúl  González    17          6205
2     Jimena     Rosas    20          7300
3  Alejandra   Saldaña    21          7665

In [68]:
clase_estadistica['Estado de origen'] = ['Zacatecas','Nuevo Leon','Tamaulipas','Sinaloa']

In [69]:
clase_estadistica

Nombre  Apellido  Edad  Edad en días Estado de origen
0       Juan     Pérez    23          8395        Zacatecas
1       Raúl  González    17          6205       Nuevo Leon
2     Jimena     Rosas    20          7300       Tamaulipas
3  Alejandra   Saldaña    21          7665          Sinaloa

In [73]:
clase_estadistica['Apellido']

0       Pérez
1    González
2       Rosas
3     Saldaña
Name: Apellido, dtype: object

In [74]:
clase_estadistica[['Apellido','Edad']]

Apellido  Edad
0     Pérez    23
1  González    17
2     Rosas    20
3   Saldaña    21

In [79]:
clase_estadistica[0:2]

Nombre  Apellido  Edad  Edad en días Estado de origen
0   Juan     Pérez    23          8395        Zacatecas
1   Raúl  González    17          6205       Nuevo Leon

In [80]:
clase_estadistica[0:2][['Apellido','Edad']]

Apellido  Edad
0     Pérez    23
1  González    17

## .iloc [Filas][Columnas]

In [85]:
clase_estadistica.iloc[:,2]

0    23
1    17
2    20
3    21
Name: Edad, dtype: int64

In [87]:
clase_estadistica.iloc[0:2,[0,2]]

Nombre  Edad
0   Juan    23
1   Raúl    17

In [87]:
clase_estadistica.iloc[0:2,[0,2]]

Nombre  Edad
0   Juan    23
1   Raúl    17

## .loc [Etiqueta/Nombre]

In [88]:
clase_estadistica.loc[:,'Edad']

0    23
1    17
2    20
3    21
Name: Edad, dtype: int64

In [90]:
clase_estadistica.loc[:,['Edad','Nombre']]

Edad     Nombre
0    23       Juan
1    17       Raúl
2    20     Jimena
3    21  Alejandra

## SQL

In [91]:
clase_estadistica.Edad

0    23
1    17
2    20
3    21
Name: Edad, dtype: int64

## Por condicionales

In [92]:
clase_estadistica[clase_estadistica['Edad']>=18]

Nombre Apellido  Edad  Edad en días Estado de origen
0       Juan    Pérez    23          8395        Zacatecas
2     Jimena    Rosas    20          7300       Tamaulipas
3  Alejandra  Saldaña    21          7665          Sinaloa

## Ordenar DataFrame

In [95]:
clase_estadistica.sort_values('Edad',ascending=True)

Nombre  Apellido  Edad  Edad en días Estado de origen
1       Raúl  González    17          6205       Nuevo Leon
2     Jimena     Rosas    20          7300       Tamaulipas
3  Alejandra   Saldaña    21          7665          Sinaloa
0       Juan     Pérez    23          8395        Zacatecas

In [98]:
clase_estadistica.sort_values(['Apellido','Nombre'],ascending=[True,True])

Nombre  Apellido  Edad  Edad en días Estado de origen
1       Raúl  González    17          6205       Nuevo Leon
0       Juan     Pérez    23          8395        Zacatecas
2     Jimena     Rosas    20          7300       Tamaulipas
3  Alejandra   Saldaña    21          7665          Sinaloa

In [99]:
clase_estadistica['Edad'].mean()

20.25

In [100]:
clase_estadistica['Edad'].var(ddof=1)

6.25

In [108]:
clase_estadistica[clase_estadistica['Edad']>=18]['Edad'].mean()

21.333333333333332

## Condicionales

In [109]:
clase_estadistica['Mayoria de edad']=np.where(clase_estadistica['Edad']>=18,'Mayor de edad','Menor de edad')

In [110]:
clase_estadistica

Nombre  Apellido  Edad  Edad en días Estado de origen Mayoria de edad
0       Juan     Pérez    23          8395        Zacatecas   Mayor de edad
1       Raúl  González    17          6205       Nuevo Leon   Menor de edad
2     Jimena     Rosas    20          7300       Tamaulipas   Mayor de edad
3  Alejandra   Saldaña    21          7665          Sinaloa   Mayor de edad

In [113]:
conditions = [clase_estadistica['Edad'] <= 17, 
              clase_estadistica['Edad'] < 23, 
              clase_estadistica['Edad'] >= 23]
choices = ['Preparatoria', 'estudia licenciatura', 'egresado licenciatura']
clase_estadistica['edad_escolar'] = np.select(conditions, choices, default='Invalid')

In [114]:
clase_estadistica

Nombre  Apellido  Edad  Edad en días Estado de origen Mayoria de edad  \
0       Juan     Pérez    23          8395        Zacatecas   Mayor de edad   
1       Raúl  González    17          6205       Nuevo Leon   Menor de edad   
2     Jimena     Rosas    20          7300       Tamaulipas   Mayor de edad   
3  Alejandra   Saldaña    21          7665          Sinaloa   Mayor de edad   

            edad_escolar  
0  egresado licenciatura  
1           Preparatoria  
2   estudia licenciatura  
3   estudia licenciatura